import type { IncomingMessage, Server } from "node:http";
import { WebSocketServer, type WebSocket } from "ws";

import { logger } from "../lib/logger";

type Digits = 2 | 3 | 4;
type Role = "host" | "guest";
type FeedbackLevel = "low" | "tooLow" | "high" | "tooHigh";

type Feedback = {
  correct: boolean;
  level: FeedbackLevel | null;
  // null for 2-digit mode (spec: only show count for 3- and 4-digit).
  correctDigitCount: number | null;
};

type GuessEntry = {
  guess: string;
  feedback: Feedback;
  at: number;
};

type Status = "waiting" | "playing" | "won";

type RoomInternal = {
  code: string;
  digits: Digits;
  hostName: string;
  guestName: string;
  guestJoined: boolean;
  // Hidden is generated by the server and never sent to clients until won.
  hidden: string;
  status: Status;
  winner: Role | null;
  hostHistory: GuessEntry[];
  guestHistory: GuessEntry[];
};

// Per-socket payload — never leaks the opponent's guesses or the hidden
// number until the game is won.
type PlayerView = {
  code: string;
  digits: Digits;
  hostName: string;
  guestName: string;
  guestJoined: boolean;
  status: Status;
  winner: Role | null;
  yourRole: Role;
  yourHistory: GuessEntry[];
  opponentGuessCount: number;
  // Only populated when status === "won".
  revealedHidden: string | null;
};

const DISTANCE_THRESHOLDS: Record<Digits, number> = { 2: 10, 3: 50, 4: 200 };

const ROOM_TTL_MS = 1000 * 60 * 60 * 4;
const rooms = new Map<string, { room: RoomInternal; updatedAt: number }>();
const subscribers = new Map<string, Set<WebSocket>>();
const socketRooms = new WeakMap<WebSocket, Set<string>>();

type Identity = { code: string; role: Role };
const socketIdentity = new WeakMap<WebSocket, Identity>();

const CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function generateRoomCode(): string {
  let out = "";
  for (let i = 0; i < 5; i++) {
    out += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
  }
  return out;
}

function generateHidden(digits: Digits): string {
  // Allow leading zeros so e.g. "027" is a valid 3-digit secret. The lobby
  // always treats hidden as a string the same length as `digits`.
  let out = "";
  for (let i = 0; i < digits; i++) out += Math.floor(Math.random() * 10).toString();
  return out;
}

function countSharedDigits(a: string, b: string): number {
  const counts: Record<string, number> = {};
  for (const ch of a) counts[ch] = (counts[ch] ?? 0) + 1;
  let shared = 0;
  for (const ch of b) {
    if ((counts[ch] ?? 0) > 0) {
      shared++;
      counts[ch]!--;
    }
  }
  return shared;
}

function evaluateGuess(guess: string, hidden: string, digits: Digits): Feedback {
  const correct = guess === hidden;
  const showCount = digits >= 3;
  const correctDigitCount = showCount ? countSharedDigits(guess, hidden) : null;
  if (correct) return { correct: true, level: null, correctDigitCount };
  const g = parseInt(guess, 10);
  const h = parseInt(hidden, 10);
  const diff = Math.abs(g - h);
  const threshold = DISTANCE_THRESHOLDS[digits];
  const level: FeedbackLevel = g < h
    ? diff <= threshold ? "low" : "tooLow"
    : diff <= threshold ? "high" : "tooHigh";
  return { correct: false, level, correctDigitCount };
}

function getRoom(code: string): RoomInternal | null {
  const r = rooms.get(code);
  return r ? r.room : null;
}

function touch(code: string) {
  const r = rooms.get(code);
  if (r) r.updatedAt = Date.now();
}

function buildView(room: RoomInternal, role: Role): PlayerView {
  const isHost = role === "host";
  const yourHistory = isHost ? room.hostHistory : room.guestHistory;
  const opponentGuessCount = isHost ? room.guestHistory.length : room.hostHistory.length;
  return {
    code: room.code,
    digits: room.digits,
    hostName: room.hostName,
    guestName: room.guestName,
    guestJoined: room.guestJoined,
    status: room.status,
    winner: room.winner,
    yourRole: role,
    yourHistory,
    opponentGuessCount,
    revealedHidden: room.status === "won" ? room.hidden : null,
  };
}

function sendState(ws: WebSocket, room: RoomInternal) {
  const id = socketIdentity.get(ws);
  if (!id || id.code !== room.code) return; // Don't send privileged state to non-players.
  if (ws.readyState !== ws.OPEN) return;
  ws.send(JSON.stringify({ type: "state", state: buildView(room, id.role) }));
}

function broadcast(code: string) {
  const room = getRoom(code);
  if (!room) return;
  touch(code);
  const subs = subscribers.get(code);
  if (!subs) return;
  for (const ws of subs) sendState(ws, room);
}

function subscribe(ws: WebSocket, code: string) {
  let set = subscribers.get(code);
  if (!set) {
    set = new Set();
    subscribers.set(code, set);
  }
  set.add(ws);
  let codes = socketRooms.get(ws);
  if (!codes) {
    codes = new Set();
    socketRooms.set(ws, codes);
  }
  codes.add(code);
  const room = getRoom(code);
  if (room) sendState(ws, room);
}

function safeSend(ws: WebSocket, msg: unknown) {
  if (ws.readyState === ws.OPEN) ws.send(JSON.stringify(msg));
}

type ClientMessage =
  | { type: "create"; reqId?: string; digits: Digits; hostName: string }
  | { type: "join"; reqId?: string; code: string; guestName: string }
  | { type: "getRoom"; reqId?: string; code: string }
  | { type: "subscribe"; code: string }
  | { type: "guess"; code: string; guess: string }
  | { type: "rematch"; code: string }
  | { type: "leave"; code: string }
  | { type: "ping"; reqId?: string };

// Public room metadata returned by getRoom (no privileged data).
type PublicRoomMeta = {
  code: string;
  digits: Digits;
  guestJoined: boolean;
  status: Status;
};

function publicMeta(room: RoomInternal): PublicRoomMeta {
  return {
    code: room.code,
    digits: room.digits,
    guestJoined: room.guestJoined,
    status: room.status,
  };
}

function handleMessage(ws: WebSocket, raw: ClientMessage) {
  switch (raw.type) {
    case "create": {
      const digits = ([2, 3, 4] as const).includes(raw.digits) ? raw.digits : 3;
      let code = generateRoomCode();
      while (rooms.has(code)) code = generateRoomCode();
      const room: RoomInternal = {
        code,
        digits,
        hostName: String(raw.hostName || "Player 1").slice(0, 24),
        guestName: "Player 2",
        guestJoined: false,
        hidden: generateHidden(digits),
        status: "waiting",
        winner: null,
        hostHistory: [],
        guestHistory: [],
      };
      rooms.set(code, { room, updatedAt: Date.now() });
      socketIdentity.set(ws, { code, role: "host" });
      subscribe(ws, code);
      safeSend(ws, {
        type: "createResult",
        reqId: raw.reqId,
        state: buildView(room, "host"),
      });
      logger.info({ code, digits }, "ws: room created");
      break;
    }
    case "join": {
      const code = String(raw.code || "").toUpperCase();
      const room = getRoom(code);
      if (!room) {
        safeSend(ws, { type: "joinResult", reqId: raw.reqId, state: null });
        return;
      }
      // Enforce 2-player capacity. Anyone with the code could otherwise
      // join and start receiving the guest's private state stream.
      const existing = socketIdentity.get(ws);
      const isExistingGuest = existing && existing.code === code && existing.role === "guest";
      if (room.guestJoined && !isExistingGuest) {
        safeSend(ws, { type: "joinResult", reqId: raw.reqId, state: null });
        logger.warn({ code }, "ws: join rejected — room full");
        return;
      }
      room.guestName = String(raw.guestName || "Player 2").slice(0, 24);
      room.guestJoined = true;
      if (room.status === "waiting") room.status = "playing";
      socketIdentity.set(ws, { code, role: "guest" });
      subscribe(ws, code);
      safeSend(ws, {
        type: "joinResult",
        reqId: raw.reqId,
        state: buildView(room, "guest"),
      });
      broadcast(code);
      logger.info({ code }, "ws: guest joined");
      break;
    }
    case "getRoom": {
      // Lobby probes existence + digit length BEFORE having an identity, so
      // we return only public, non-privileged metadata.
      const room = getRoom(String(raw.code || "").toUpperCase());
      safeSend(ws, {
        type: "getRoomResult",
        reqId: raw.reqId,
        meta: room ? publicMeta(room) : null,
      });
      break;
    }
    case "subscribe": {
      subscribe(ws, String(raw.code || "").toUpperCase());
      break;
    }
    case "guess": {
      const code = String(raw.code).toUpperCase();
      const id = socketIdentity.get(ws);
      if (!id || id.code !== code) return;
      const room = getRoom(code);
      if (!room || room.status !== "playing") return;
      if (!/^[0-9]+$/.test(raw.guess) || raw.guess.length !== room.digits) return;

      const fb = evaluateGuess(raw.guess, room.hidden, room.digits);
      const entry: GuessEntry = { guess: raw.guess, feedback: fb, at: Date.now() };
      if (id.role === "host") room.hostHistory = [entry, ...room.hostHistory];
      else room.guestHistory = [entry, ...room.guestHistory];

      if (fb.correct) {
        room.status = "won";
        room.winner = id.role;
        // Reveal hidden + final winner to BOTH players.
        broadcast(code);
      } else {
        // Send personal feedback to the guesser only; also push opponent
        // "guessing" tick to the other side so they see the opponent counter.
        touch(code);
        sendState(ws, room);
        const subs = subscribers.get(code);
        if (subs) {
          for (const peer of subs) {
            if (peer !== ws) sendState(peer, room);
          }
        }
      }
      break;
    }
    case "rematch": {
      const code = String(raw.code).toUpperCase();
      const id = socketIdentity.get(ws);
      if (!id || id.code !== code) return;
      const room = getRoom(code);
      if (!room) return;
      // Either player can request a rematch once the previous game is won.
      if (room.status !== "won") return;
      room.hidden = generateHidden(room.digits);
      room.hostHistory = [];
      room.guestHistory = [];
      room.winner = null;
      room.status = room.guestJoined ? "playing" : "waiting";
      broadcast(code);
      logger.info({ code }, "ws: rematch started");
      break;
    }
    case "leave": {
      const code = String(raw.code).toUpperCase();
      const id = socketIdentity.get(ws);
      // Either player leaving closes the room — both players need to know
      // the game is over.
      if (id && id.code === code) {
        rooms.delete(code);
        const subs = subscribers.get(code);
        if (subs) {
          for (const peer of subs) {
            safeSend(peer, { type: "roomClosed", code });
          }
          subscribers.delete(code);
        }
        logger.info({ code, by: id.role }, "ws: room closed");
      } else {
        subscribers.get(code)?.delete(ws);
        const set = subscribers.get(code);
        if (set && set.size === 0) subscribers.delete(code);
      }
      break;
    }
    case "ping": {
      safeSend(ws, { type: "pong", reqId: raw.reqId });
      break;
    }
  }
}

setInterval(() => {
  const now = Date.now();
  for (const [code, r] of rooms) {
    if (now - r.updatedAt > ROOM_TTL_MS) {
      rooms.delete(code);
      subscribers.delete(code);
    }
  }
}, 1000 * 60 * 30).unref?.();

export function attachGameWs(server: Server) {
  const wss = new WebSocketServer({ noServer: true });

  server.on("upgrade", (req: IncomingMessage, socket, head) => {
    try {
      const url = req.url ?? "";
      if (!url.startsWith("/api/ws")) return;
      wss.handleUpgrade(req, socket, head, (ws) => {
        wss.emit("connection", ws, req);
      });
    } catch (err) {
      logger.error({ err }, "ws: upgrade error");
      socket.destroy();
    }
  });

  wss.on("connection", (ws: WebSocket) => {
    logger.info("ws: client connected");

    let alive = true;
    ws.on("pong", () => {
      alive = true;
    });
    const heartbeat = setInterval(() => {
      if (!alive) {
        ws.terminate();
        return;
      }
      alive = false;
      try {
        ws.ping();
      } catch {
        // ignore
      }
    }, 30000);

    ws.on("message", (data) => {
      let msg: ClientMessage | null = null;
      try {
        msg = JSON.parse(data.toString()) as ClientMessage;
      } catch {
        return;
      }
      if (msg && typeof msg.type === "string") {
        try {
          handleMessage(ws, msg);
        } catch (err) {
          logger.error({ err, type: msg.type }, "ws: handler error");
        }
      }
    });

    ws.on("close", () => {
      clearInterval(heartbeat);
      const codes = socketRooms.get(ws);
      if (codes) {
        for (const code of codes) {
          subscribers.get(code)?.delete(ws);
          const set = subscribers.get(code);
          if (set && set.size === 0) subscribers.delete(code);
        }
      }
      // If this socket was a player (host/guest), closing it ends the game
      // — notify the opponent and tear the room down, matching `leave`.
      const id = socketIdentity.get(ws);
      if (id && rooms.has(id.code)) {
        const code = id.code;
        rooms.delete(code);
        const subs = subscribers.get(code);
        if (subs) {
          for (const peer of subs) {
            safeSend(peer, { type: "roomClosed", code });
          }
          subscribers.delete(code);
        }
        logger.info({ code, by: id.role }, "ws: room closed via disconnect");
      }
    });

    ws.on("error", (err) => {
      logger.warn({ err }, "ws: socket error");
    });
  });

  logger.info("ws: game socket attached at /api/ws");
}
