kind = "mobile"
previewPath = "/"
title = "Number Hunt"
version = "1.0.0"
id = "artifacts/number-hunt"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21604

[services.development]
run = "pnpm --filter @workspace/number-hunt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/number-hunt", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/number-hunt", "run", "serve" ]

[services.env]
PORT = "21604"
BASE_PATH = "/"
